name: Create stable release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: gbannerman/mopidy-pibox/.github/workflows/build.yml@main

  publish_py:
    name: Publish python package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download built Python package
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}-mopidy-pibox
          path: dist

      - name: Install twine
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install twine==5.0.0

      - name: Init .pypirc
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          echo -e "[pypi]" >> ~/.pypirc
          echo -e "username = gbannerman" >> ~/.pypirc
          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - name: Upload to pypi
        run: |
          . venv/bin/activate
          twine upload dist/*
